# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: text_api
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    command: uwsgi --http 0.0.0.0:5000 --module text_api.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/text_api.db
    volumes:
      - ./text_api:/code/text_api
      - ./db/:/db/
    ports:
      - "5000:5000"
