# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: text_api
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    command: gunicorn -b 0.0.0.0:5000 text_api.wsgi:app --timeout=1200 --log-level=debug  # text_api run -h 0.0.0.0  # uwsgi --ini text_api.ini --http 0.0.0.0:5000 --module text_api.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/text_api.db
    volumes:
      - ./text_api:/code/text_api
      - ./db/:/db/
    ports:
      - "5000:5000"

  redis:
    image: redis

  celery:
    image: text_api
    command: "celery -A text_api.celery_app:app worker --loglevel=info"
    env_file:
      - ./.flaskenv
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND_URL=redis://redis:6379/0
      - DATABASE_URI=sqlite:////code/db/text_api.db
