version: '3'

volumes:
  production_sqli: { }

services:
  flask_web:
    build:
      context: .
      dockerfile: ./compose/production/flask/Dockerfile
    image: text_api
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////code/db/text_api.db
    volumes:
      - production_sqli:/code/db/
    command: gunicorn -b 0.0.0.0:5000 text_api.wsgi:app --timeout=1200

  frontend:
    build:
      context: .
      dockerfile: ./compose/production/node/Dockerfile
    image: text_frontend
    env_file:
      - ./.vueenv
    ports:
      - "8080:80"

  redis:
    image: redis

  celery:
    image: text_api
    command: "celery -A text_api.celery_app:app worker"
    env_file:
      - ./.flaskenv
    volumes:
      - production_sqli:/code/db/
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND_URL=redis://redis:6379/0
      - DATABASE_URI=sqlite:////code/db/text_api.db
